routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SeminarController;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\RegisteredUserController;
use App\Http\Controllers\SeminarVideoController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Auth.index');
})->name('login');

Route::get('/registration', function () {
    return view('Auth.register');
})->name('registration');


Route::controller(UserController::class)->group(function () {
	Route::get('registration-verify/{token}','showVerifyEmail')->name('registration_verify.get');
	Route::post('registration','store')->name('registration.store');
    Route::get('registration-success', 'success')->name('registration.success');
});

//Authentications/Login
Route::group(['prefix'=> 'auth'], function(){
	Route::name('auth.')->group(function () {
		// For Login
		Route::controller(AuthController::class)->group(function () {
	 		 Route::post('request', 'authenticate')->name('authenticate');
	 		 Route::get('test', 'test')->name('test');
		});

		// For Forgot Password
		Route::controller(ForgotPasswordController::class)->group(function () {
			Route::get('forget-password', 'index')->name('forget.password.get');
			Route::post('forget-password','store')->name('forget.password.post');
			Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
			Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
			Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
			Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
		});
	});});


// Route::get('account/', 'AccountController@index')->name('account.index');

Route::group(['prefix'=> 'account', 'middleware' => ['auth']], function(){

    Route::name('account.')->group(function () {
        // Main Manager Page
        Route::controller(AccountController::class)->group(function () {
            Route::get('','index')->name('index');
        });

        //seminar list
        Route::controller(SeminarController::class)->group(function () {
            Route::get('seminar/{date_from?}/{date_to?}','index')->name('seminar'); //this would be seminar list
            Route::get('seminar-list','list')->name('seminar.list'); //this would be seminar list
            Route::get('seminar-detail/{id?}/{date_from?}/{date_to?}','showSeminarDetail')->name('seminar.detail.get');
            Route::get('seminar-detail-list/{id}','showSeminarDetailList')->name('seminar.detail.list');
            Route::get('seminar-status/{id?}','showSeminarStatus')->name('seminar.status');
            Route::get('seminar-export-excel/{id?}', 'exportSeminarDetail')->name('seminar.export.excel');// Route for export/download tabledata to .csv, .xls or .xlsx

            // Qrcode
            Route::get('seminar-today-listing','seminarToday')->name('seminar.today'); //this is qrcode scanner 
            Route::get('seminar-qrcode/{id?}','qrcodeScanner')->name('seminar.qrcode'); //this is qrcode scanner 
            Route::post('seminar-qrcode-scan','qrcodeScan')->name('seminar.qrcode_scan'); //this qrcode scanner function
            Route::get('seminar-qrcode-status/{status?}/{id?}','qrcodeStatus')->name('seminar.qrcode_status'); //this is qrcode status if time in or time out
            Route::get('seminar-qrcode-error/{id?}','qrcodeStatusError')->name('seminar.qrcode_status_error'); //this is qrcode error
            Route::get('seminar-qrcode-error-code/{id?}','qrcodeStatusErrorSeminar')->name('seminar.qrcode_status_error_seminar'); //this is qrcode error
            Route::get('seminar-qrcode-error-exam/{id?}','qrcodeStatusErrorExam')->name('seminar.qrcode_status_error_exam'); //this is qrcode error
            Route::get('seminar-qrcode-auth/{status?}/{id?}','qrcodeAuth')->name('seminar.qrcode_auth'); //this is qrcode error
            Route::post('seminar-qrcode-authenticate','qrcodeAuthBack')->name('seminar.qrcode_auth_back'); //this is qrcode error


            //search seminar
            Route::post('seminar-filter/{id?}','filterSeminar')->name('seminar.filter');
            Route::get('user-seminar-status/{id?}','getUserSeminarStatus')->name('seminar.user.status');
            Route::post('user-seminar-update-reception','updateUserSeminarReception')->name('seminar.user.seminar.reception.update');
        });

        // User
         Route::controller(RegisteredUserController::class)->group(function () {
            Route::get('email-authentication-status','showUnverifiedUser')->name('user.unverified');
            Route::get('user-unverified','listUnverifiedUser')->name('user.unverified.list');
            Route::get('verify-user/{id?}','verifyUser')->name('user.set.verify');

        });

    });

 	Route::name('seminar_exam.')->group(function () {
        // Seminar Exam
        Route::controller(ExamController::class)->group(function () {
            Route::get('seminar-exam/','index')->name('index');
            Route::get('seminar-exam-list/','list')->name('list');
            Route::get('seminar-exam-show/{seminar_id?}','show')->name('show');
            Route::post('seminar-exam-store/','store')->name('store');


            Route::get('seminar-exam-seminar-detail/{seminar_id?}','seminarDetail')->name('seminar_detail');
            Route::get('seminar-exam-seminar-edit/{seminar_id}','seminar_detail_edit')->name('seminar_edit');
            Route::post('seminar-exam-seminar-edit/{seminar_id}','seminar_detail_edit_save')->name('seminar_edit_save');
            Route::get('seminar-exam-seminar-add/','seminar_add')->name('seminar_add'); 
            Route::post('seminar-exam-seminar-save/','seminarStore')->name('seminar_store'); 

            Route::get('change-exam-answer/','changeExam')->name('change_exam');          
            Route::get('change-exam-answer-list/','changeExamList')->name('exam_list');
            Route::get('change-exam-answer-list-detail/{seminar_registration_id}','changeExamListDetail')->name('exam_list_detail'); 
            Route::post('change-exam-answer-list-detail-save/','changeExamListDetailstore')->name('exam_list_detail_store');   
            // Route::get('change-exam-answer-edit/{id?}','changeExamEdit')->name('exam_edit');

                 
                
        });

    });

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});


// video on demand
Route::group(['prefix'=> 'delivery-video', 'as' => 'SeminarVideo.', 'middleware' => ['auth']], function(){
    Route::controller(SeminarVideoController::class)->group(function () {
        Route::get('','index')->name('index');
        Route::get('list','list')->name('list');
        Route::get('details/{seminar_id?}/{id?}','details')->name('details');
        Route::post('save','saveSeminarVideo')->name('save');
        Route::get('upload/{seminar_id?}/{id?}','upload')->name('upload');
        Route::get('delete/{seminar_id?}','deleteFile')->name('delete');
        Route::post('upload','uploadFile')->name('upload.file');
    });
});

app/Models/SeminarVideo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SeminarVideo extends Model
{
    use HasFactory;
    protected $primaryKey = 'id';

    protected $table = 'seminar_videos';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'm_seminar_id',
        'video_open_at',
        'video_close_at',
        'm3u8file_path',
        'keep_original_flag',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */

}

app/Http/Controllers/SeminarVideoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\SeminarVideo;
use App\Models\Seminar;
use Validator;
use File;

class SeminarVideoController extends Controller
{
    public function index(){
        return view('SeminarVideo.index');
    }

    public function saveSeminarVideo(Request $request){

        $seminar_id = $request->get('seminar_id');
        $id = $request->get('id');
        $video_open_at = $request->get('video_open_at');
        $video_close_at = $request->get('video_close_at');

        $validator = Validator::make($request->all(), [
            'video_open_at' => 'required',
            'video_close_at' => 'required',
            'upload_file' => 'required'
        ],[
            'upload_file.required' => '動画がアップロードされていません'
        ]);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'error' => $validator->errors()]);   
        }else{

            if (!empty($seminar_id)) {
                $video =  SeminarVideo::where('m_seminar_id', $seminar_id)->first();
                $video->video_open_at = $video_open_at;
                $video->video_close_at = $video_close_at;
                if ($video->save()) {
                    return response()->json(['status' => true, 'redirect' => route('SeminarVideo.index')]);
                }
            }else{
                $video = new SeminarVideo;
            }
            $video->video_open_at = $video_open_at;
            $video->video_close_at = $video_close_at;
            if ($video->save()) {
                return response()->json(['status' => true, 'redirect' => route('SeminarVideo.index')]);
            }

        }
    }

    public function details($seminar_id, $id = '', Request $request){
        $details = [];

        if (!empty($id)) {
        $details = Seminar::with(['video' => function($q) use($id){
                $q->where('id', $id);
            }])->where('id', $seminar_id)->orderBy('start_at', 'desc')->firstOrFail();
        }else{
         $details = Seminar::with(['video'])->where('id', $seminar_id)->orderBy('start_at', 'desc')->firstOrFail();
        }

        return view('SeminarVideo.details', compact('details' , 'seminar_id', 'id', 'request'));
    }


    public function upload($seminar_id, $id = '', Request $request){
        $details = (!empty($id))? SeminarVideo::find($id): [];
        return view('SeminarVideo.upload', compact('id' , 'seminar_id' , 'details', 'request'));
    }

    public function uploadFile(Request $request){
        $seminar_id = $request->get('seminar_id');
        $file_name = $request->get('file_name');
        $flag = $request->get('flag');
        $video_id = $request->get('video_id');
        $video_times = $request->get('video_times');

       $validator = Validator::make($request->all(), [
            'upload_file' => 'required',
            'video_times' => 'required'
       ]); 

       if ($validator->fails()) {
           return response()->json(['status' => false, 'error' => $validator->errors()]);
       }else{

        $has_video = SeminarVideo::where('m_seminar_id', $seminar_id);
        if ($has_video->count() > 0) {
            $video = $has_video->first();
        }else{
            $video = new SeminarVideo;
        }
            

        $new_file_name = str_replace([' ', '\'', '(', ')', '-', '"'], '_', $file_name);

        $file = request()->file('upload_file');
        $file->storePubliclyAs($seminar_id, $new_file_name, 'video');
        $video->m3u8file_path = $new_file_name;
        $video->m_seminar_id = $seminar_id;
        $video->keep_original_flag = $flag;
        $video->video_times = $video_times;
        if ($video->save()) {

             $path = public_path('/video/'.$video->m_seminar_id);
             $source_path = str_replace('\\', '/', $path);

            exec('ffmpeg -i '.$path.'/'.$video->m3u8file_path.' -c:v copy -c:a copy -f hls -hls_time 9 -hls_playlist_type vod -hls_segment_filename "'.$path.'/video%3d.ts" '.$path.'/video.m3u8', $output, $intercount);

            if ($intercount == 0) {
                if ($flag !== 1) {
                    if (File::exists($source_path.'/'.$new_file_name)) {
                        File::deleteDirectory($source_path.'/'.$new_file_name);
                    }    
                }

                return response()->json(['status' => true, 'redirect' => route('SeminarVideo.details', [$seminar_id, $video->id]) ]);
            }else{
                $validator->errors()->add('upload_file','Failed to upload file. please try again.');
                return response()->json(['status' => false, 'error' => $validator->errors()]);
            }
             

        }
       }
    }

    public function deleteFile($id){
        $has_video = SeminarVideo::where('id', $id);
        if ($has_video->count() > 0) {
            $video = $has_video->first();
            
            $source_path = public_path('/video/'.$video->m_seminar_id.'/'.$video->m3u8file_path);
            // $source_path = str_replace('/', '\\', $path);

            if (File::exists($source_path)) {
                File::deleteDirectory($source_path);
            }    

            $video->m3u8file_path = null;
            $video->video_open_at = null;
            $video->video_close_at = null;
            $video->keep_original_flag = null;
            $video->video_times = null;
            if ($video->save()) {
                 return redirect(route('SeminarVideo.details', [$video->m_seminar_id, $id]));
             }
        }

    }


    public function list(){
        $today = now();
        $seminar = Seminar::with(['video' => function($q) use($today){
            $q->where('video_close_at', '>=', date('Y-m-d', strtotime($today)))
            ->orWhere(function($query){
                $query->whereNull('video_close_at');
            });
        }])->orderBy('start_at', 'desc')->get();

        return response()->json(['status' => true, 'data' => $seminar]);
    }
}

resources/views/SeminarVideo/details.blade.php
@extends('Layout.account.app')
@section('title', '配信動画詳細')

@section('css')
<link rel="stylesheet" type="text/css" href="{{ asset('css/video.css') }}">
@endsection

@section('content')
<form id="submit_details_form" class="needs-validation" action="{{ route('SeminarVideo.save') }}" method="post" novalidate="">

  <input type="hidden" name="seminar_id" id="seminar_id" value="{{ $seminar_id ?? '' }}">
  <input type="hidden" name="id" id="id" value="{{ $id ?? '' }}">
	<div class="row justify-content-center mt-5">
    <div class="col-md-10 col-12">
        <div class="row justify-content-center">
        <!-- form label start -->
        <div class="col-sm-12">
          <label class="page-title">配信動画詳細</label>
        </div>
        <div class="col-12 col-md-12">
          <div class="row">
            <div class="col-md-3">
                <div class="input-group mb-3">
                  <div class="input-group-prepend bg-primary input-label">
                    <span class="input-group-text bg-primary border-0" id="basic-addon1">開催日</span>
                  </div>
                  <input type="text" class="form-control bg-white col-md-5 text-center border-0" readonly="" aria-describedby="basic-addon1" value="{{ $details->seminar_date ?? '' }}">
                </div>
            </div>
            <div class="col-md-3 ">
                <div class="input-group mb-3">
                  <div class="input-group-prepend bg-primary input-label">
                    <span class="input-group-text bg-primary border-0" id="basic-addon1">領域</span>
                  </div>
                  <input type="text" class="form-control bg-white text-center border-0" readonly="" aria-describedby="basic-addon1" value="{{ $details->category_no ?? '' }}">
                </div>
            </div>
            <div class="col-md-4">
                <div class="input-group mb-3">
                  <div class="input-group-prepend bg-primary input-label">
                    <span class="input-group-text bg-primary border-0" id="basic-addon1">セミナー項目</span>
                  </div>
                  <input type="text" class="form-control bg-white border-0" readonly="" aria-describedby="basic-addon1" value="{{ $details->category_name ?? '' }}">
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="input-group mb-3">
            <div class="input-group-prepend bg-primary input-label">
              <span class="input-group-text bg-primary border-0" id="basic-addon1">配信開始</span>
            </div>
            <input type="datetime-local" class="form-control col-md-3" aria-describedby="basic-addon1" name="video_open_at" id="video_open_at" value="{{ $details->video->video_open_at ??  $request->get('open') }}">
            <div class="invalid-feedback" id="err_video_open_at"></div>
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend bg-primary input-label">
              <span class="input-group-text bg-primary border-0" id="basic-addon1">配信終了</span>
            </div>
            <input type="datetime-local" class="form-control col-md-3" aria-describedby="basic-addon1" name="video_close_at" id="video_close_at" value="{{ $details->video->video_close_at ??  $request->get('close') }}">
            <div class="invalid-feedback" id="err_video_close_at"></div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6">
            <input type="hidden" class="form-control col-md-2" aria-describedby="basic-addon1" name="upload_file" id="upload_file" value="{{ $details->video->m3u8file_path ?? '' }}">
            <div class="invalid-feedback" id="err_upload_file"></div>
              @if(!empty($details->video->m3u8file_path))
                <P>ビデオアップロード済</P>
                <a href="{{ route('SeminarVideo.delete', [$id]) }}" class="btn btn-danger px-5">動画削除 </a>
              @endif
            </div>
            <div class="col-md-6 text-right">
              @if(!empty($details->video->m3u8file_path))
                <br>

                @if($details->video->keep_original_flag == 1)
                  <a href="{{ asset('video/'.$details->id.'/'.$details->video->m3u8file_path) }}" download="" class="btn btn-primary px-4">動画ダウンロード</a>
                @endif
              @else
                <br>
                <button type="button" onclick="upload_video('{{ route('SeminarVideo.upload', [$seminar_id, $id]) }}?');" class="btn btn-primary px-4">動画アップロード</button>
              @endif
            </div>
            <div class="col-md-12 text-right mt-2">
                <button type="submit" class="btn btn-primary px-4 mr-2">保存</button>
                <a href="{{ route('SeminarVideo.index') }}" class="btn btn-warning px-4">戻る</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
@endsection

@section('script')

<script src="{{ asset('js/video.js?1') }}"></script>
<script src="{{ asset('js/hls.js?1') }}"></script>

<script type="text/javascript">
  $("#submit_details_form").on('submit', function(e){
    e.preventDefault();
    let url = $(this).attr('action');
    let formData = $(this).serialize();
    $.ajax({
        type:"POST",
        url:url,
        data:formData,
        dataType:'json',
        beforeSend:function(){
        },
        success:function(response){
          // console.log(response);
         if (response.status == true) {
          window.location = response.redirect;
         }else{
          showValidator(response.error, 'submit_details_form');
         }
        },
        error: function(error){
          console.log(error);
        }
      });
  });

</script>
@endsection

resources/views/SeminarVideo/index.blade.php
@extends('Layout.account.app')
@section('title', '配信動画管理')

@section('css')
@endsection

@section('content')
	<div class="row justify-content-center mt-5">
    <div class="col-md-10 col-12">
        <div class="row justify-content-center">
        <!-- form label start -->
        <div class="col-sm-12">
          <label class="page-title">配信動画管理</label>
        </div>
        <div class="col-12 col-md-12">
          <table class="table dt-responsive table-bordered" id="tbl_seminar_video" style="width: 100%;"></table>
        </div>
        <div class="col-sm-12 text-right mt-2">
          <a href="{{ route('account.index') }}" class="btn btn-warning">戻る</a>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
<script type="text/javascript">
  show_seminar_video();

  function show_seminar_video(){
    $('#tbl_seminar_video').DataTable({
        pageLength: 10,
        responsive: true,
        ajax: {
          url: '{{ route('SeminarVideo.list') }}',
          error: function (xhr, error, code) {
              setTimeout(function(){
                show_seminar_video();
              },1500);
          }
        },
        searchable: false,
        "bLengthChange": false,
        "info": false,
        aaSorting: [],
        "bFilter": false,
        deferRender: false,
        language: {
        "emptyTable": "データなし",
        "paginate": {
          "previous": "前",
          "next": "次",
        }
      },
        columns: [{
        className: '',
        "data": "seminar_date",
        "title": "開催日",
      },{
        className: '',
        "data": "category_no",
        "title": "領域",
      },{
        className: '',
        "data": "category_name",
        "title": "セミナー項目",
      },{
        className: '',
        "data" : 'video',
        "title": "配信開始",
          "render": function(data, type, row, meta){
          return (row.video !== null) ? row.video.video_open_at : '';
        }
      },{
        className: '',
        "data" : 'video',
        "title": "配信終了",
          "render": function(data, type, row, meta){
          return (row.video !== null)? row.video.video_close_at : '';
        }
      },{
        className: 'width-option-1 text-center',
        "data": "id",
        "orderable": false,
        "title": "編集",
          "render": function(data, type, row, meta){
            newdata = '';
            let video_parameter = (row.video !== null)? '/'+row.video.id : '';
            newdata += '<a href="{{ route("SeminarVideo.details") }}/'+row.id+video_parameter+'" class="btn btn-primary btn-sm font-base mt-1" type="button">詳細</a> ';
            return newdata;
          }
        }
      ]
    });
  }
</script>
@endsection

resources/views/SeminarVideo/upload.blade.php
@extends('Layout.account.app')
@section('title', '動画アップロード')

@section('css')
@endsection

@section('content')
<form class="needs-validation" id="form_upload" action="{{ route('SeminarVideo.upload.file') }}" enctype="multipart/form-data" novalidate="">
    <div class="row justify-content-center mt-5">
      <div class="col-md-10 col-12">
          <div class="row justify-content-center">
          <!-- form label start -->
          <div class="col-sm-12">
            <label class="page-title">動画アップロード</label>
          </div>

          <div class="col-sm-12">
            <div class="row">
              <div class="input-group col-md-6 mb-3">
                <input type="file" name="upload_file" id="upload_file" class="d-none" required="" accept="video/*">
                <input type="hidden" name="seminar_id" id="seminar_id" class="d-none" value="{{ $seminar_id }}" readonly="">
                <input type="hidden" name="video_id" id="video_id" class="d-none" value="{{ $id ?? '' }}" readonly="">
                <input type="datetime-local" name="video_open_at" id="video_open_at" class="d-none" value="{{ $request->get('open') ?? '' }}" readonly="">
                <input type="datetime-local" name="video_close_at" id="video_close_at" class="d-none" value="{{ $request->get('close') ?? '' }}" readonly="">
                <input type="type" class="form-control bg-white " aria-describedby="basic-addon1" name="file_name" id="file_name" value="{{ $details->m3u8file_path ?? '' }}" readonly="">
                  <div class="input-group-append bg-primary input-label">
                  <button type="button" onclick="$('#upload_file').click();" class="input-group-text bg-primary border-0" id="basic-addon1">ファイル選択</button>
                </div>
                  <div class="invalid-feedback" id="err_upload_file"></div>
              </div>
              <div class="col-md-1"></div>
              <div class="input-group col-md-2 mb-3">
                 <div class="input-group-prepend bg-white input-label">
                    <span class="input-group-text bg-white border-0" id="basic-addon1">開催日</span>
                  </div>
                 <input type="number" max="999.9" step="0.1" class="form-control bg-white " aria-describedby="basic-addon1" name="video_times" id="video_times"  value="{{ $details->video_times ?? '' }}">
                  <div class="input-group-append bg-white input-label">
                    <span class="input-group-text bg-white border-0" id="basic-addon1"> 分</span>
                  </div>
                  <div class="invalid-feedback" style="padding-left: 6em;" id="err_video_times"></div>
              </div>
            </div>
          </div>

           <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">

                <p class="m-1"><label for="flag">オリジナルファイルを保存する</label> <input type="checkbox" name="flag" id="flag" value="1" {{ (!empty($details->keep_original_flag) && $details->keep_original_flag == 1)? 'checked' : '' }} ></p>
                <p class="m-1">(オリジナルファイルを保存すると、ダウンロードが可能となります)</p>
              </div>
              <div class="col-md-6 text-right">
                <br><button type="submit" class="btn btn-primary px-4" id="submit_btn">アップロード </button>
              </div>
              <div class="col-md-12 text-right mt-2">
                  <a href="{{ route('SeminarVideo.details', [$seminar_id, $id]) }}" class="btn btn-warning px-4">戻る</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</form>
@endsection

@section('script')
<script type="text/javascript">
  $("#form_upload").on('submit', function(e){
    e.preventDefault();
    let form = $('#form_upload')[0];
    let data = new FormData(form);
    let url = $('#form_upload').attr('action');

    $.ajax({
        type:"POST",
        url:url,
        processData: false,
        contentType: false,
        cache: false,
        data:data,
        dataType:'json',
        beforeSend:function(){
          $("#submit_btn").prop('disabled', true);
        },
        success:function(response){
           // console.log(response);
          if (response.status === true) {
            // window.location = response.redirect;
            upload_video(response.redirect+'?');
          }else{
            showValidator(response.error, 'form_upload');
          }
          $("#submit_btn").prop('disabled', false);
        },
        error: function(error){
          $("#submit_btn").prop('disabled', false);
          console.log(error);
        }
      });
  });

  $("input[type=file]").on('change',function(){
    $("#file_name").val(this.files[0].name);
  });

</script>
@endsection