routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SeminarController;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\RegisteredUserController;
use App\Http\Controllers\SeminarVideoController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('Auth.index');
})->name('login');

Route::get('/registration', function () {
    return view('Auth.register');
})->name('registration');


Route::controller(UserController::class)->group(function () {
	Route::get('registration-verify/{token}','showVerifyEmail')->name('registration_verify.get');
	Route::post('registration','store')->name('registration.store');
    Route::get('registration-success', 'success')->name('registration.success');
});

//Authentications/Login
Route::group(['prefix'=> 'auth'], function(){
	Route::name('auth.')->group(function () {
		// For Login
		Route::controller(AuthController::class)->group(function () {
	 		 Route::post('request', 'authenticate')->name('authenticate');
	 		 Route::get('test', 'test')->name('test');
		});

		// For Forgot Password
		Route::controller(ForgotPasswordController::class)->group(function () {
			Route::get('forget-password', 'index')->name('forget.password.get');
			Route::post('forget-password','store')->name('forget.password.post');
			Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
			Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
			Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
			Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
		});
	});});


// Route::get('account/', 'AccountController@index')->name('account.index');

Route::group(['prefix'=> 'account', 'middleware' => ['auth']], function(){

    Route::name('account.')->group(function () {
        // Main Manager Page
        Route::controller(AccountController::class)->group(function () {
            Route::get('','index')->name('index');
        });

        //seminar list
        Route::controller(SeminarController::class)->group(function () {
            Route::get('seminar/{date_from?}/{date_to?}','index')->name('seminar'); //this would be seminar list
            Route::get('seminar-list','list')->name('seminar.list'); //this would be seminar list
            Route::get('seminar-detail/{id?}/{date_from?}/{date_to?}','showSeminarDetail')->name('seminar.detail.get');
            Route::get('seminar-detail-list/{id}','showSeminarDetailList')->name('seminar.detail.list');
            Route::get('seminar-status/{id?}','showSeminarStatus')->name('seminar.status');
            Route::get('seminar-export-excel/{id?}', 'exportSeminarDetail')->name('seminar.export.excel');// Route for export/download tabledata to .csv, .xls or .xlsx

            // Qrcode
            Route::get('seminar-today-listing','seminarToday')->name('seminar.today'); //this is qrcode scanner 
            Route::get('seminar-qrcode/{id?}','qrcodeScanner')->name('seminar.qrcode'); //this is qrcode scanner 
            Route::post('seminar-qrcode-scan','qrcodeScan')->name('seminar.qrcode_scan'); //this qrcode scanner function
            Route::get('seminar-qrcode-status/{status?}/{id?}','qrcodeStatus')->name('seminar.qrcode_status'); //this is qrcode status if time in or time out
            Route::get('seminar-qrcode-error/{id?}','qrcodeStatusError')->name('seminar.qrcode_status_error'); //this is qrcode error
            Route::get('seminar-qrcode-error-code/{id?}','qrcodeStatusErrorSeminar')->name('seminar.qrcode_status_error_seminar'); //this is qrcode error
            Route::get('seminar-qrcode-error-exam/{id?}','qrcodeStatusErrorExam')->name('seminar.qrcode_status_error_exam'); //this is qrcode error
            Route::get('seminar-qrcode-auth/{status?}/{id?}','qrcodeAuth')->name('seminar.qrcode_auth'); //this is qrcode error
            Route::post('seminar-qrcode-authenticate','qrcodeAuthBack')->name('seminar.qrcode_auth_back'); //this is qrcode error


            //search seminar
            Route::post('seminar-filter/{id?}','filterSeminar')->name('seminar.filter');
            Route::get('user-seminar-status/{id?}','getUserSeminarStatus')->name('seminar.user.status');
            Route::post('user-seminar-update-reception','updateUserSeminarReception')->name('seminar.user.seminar.reception.update');
        });

        // User
         Route::controller(RegisteredUserController::class)->group(function () {
            Route::get('email-authentication-status','showUnverifiedUser')->name('user.unverified');
            Route::get('user-unverified','listUnverifiedUser')->name('user.unverified.list');
            Route::get('verify-user/{id?}','verifyUser')->name('user.set.verify');

        });

    });

 	Route::name('seminar_exam.')->group(function () {
        // Seminar Exam
        Route::controller(ExamController::class)->group(function () {
            Route::get('seminar-exam/','index')->name('index');
            Route::get('seminar-exam-list/','list')->name('list');
            Route::get('seminar-exam-show/{seminar_id?}','show')->name('show');
            Route::post('seminar-exam-store/','store')->name('store');


            Route::get('seminar-exam-seminar-detail/{seminar_id?}','seminarDetail')->name('seminar_detail');
            Route::get('seminar-exam-seminar-edit/{seminar_id}','seminar_detail_edit')->name('seminar_edit');
            Route::post('seminar-exam-seminar-edit/{seminar_id}','seminar_detail_edit_save')->name('seminar_edit_save');
            Route::get('seminar-exam-seminar-add/','seminar_add')->name('seminar_add'); 
            Route::post('seminar-exam-seminar-save/','seminarStore')->name('seminar_store'); 

            Route::get('change-exam-answer/','changeExam')->name('change_exam');          
            Route::get('change-exam-answer-list/','changeExamList')->name('exam_list');
            Route::get('change-exam-answer-list-detail/{seminar_registration_id}','changeExamListDetail')->name('exam_list_detail'); 
            Route::post('change-exam-answer-list-detail-save/','changeExamListDetailstore')->name('exam_list_detail_store');   
            // Route::get('change-exam-answer-edit/{id?}','changeExamEdit')->name('exam_edit');

                 
                
        });

    });

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});


// video on demand
Route::group(['prefix'=> 'delivery-video', 'as' => 'SeminarVideo.', 'middleware' => ['auth']], function(){
    Route::controller(SeminarVideoController::class)->group(function () {
        Route::get('','index')->name('index');
        Route::get('list','list')->name('list');
        Route::get('details/{seminar_id?}/{id?}','details')->name('details');
        Route::post('save','saveSeminarVideo')->name('save');
        Route::get('upload/{seminar_id?}/{id?}','upload')->name('upload');
        Route::get('delete/{seminar_id?}','deleteFile')->name('delete');
        Route::post('upload','uploadFile')->name('upload.file');
    });
});

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Validator;
use Carbon\Carbon;

use App\Models\User;
use App\Models\Seminar;
use App\Models\Exam;
use App\Models\UserExam;
use App\Models\SeminarGroup;
use App\Models\SeminarRegistration;
use DataTables;
class ExamController extends Controller
{

    public function index(){

        $user = Auth::user();
        return view('Exam.index');
    }

    public function list(Request $request){
        $today = date('Y-m-d');
        $query = [];

        if($request->checkbox_con=='true'){
             $query = Seminar::orderBy('m_seminar_group_id','desc')->orderBy('category_no','asc');
        }else{
             $query = Seminar::where('seminar_date', '>=', $today)->orderBy('m_seminar_group_id')->orderBy('category_no');
        }

        return Datatables::of($query->get())->make(true);
    }

    public function show($seminar_id){

        $seminar = Seminar::with(["exams" => function($q){ 
                    $q->orderBy('question_no');
                }])->find($seminar_id);

        if(!$seminar){
            return redirect()->route('seminar_exam.index');
        }
            
        if($seminar->exams->isEmpty()){
            //insert to exams

            $exam_data = array();
            for($i = 1; $i <= 5; $i++){

                $field['m_seminar_id'] = $seminar->id;
                $field['question_no'] = $i;
                $field['seminar_use'] = 0;
                $field['answer'] = 0;
                $field['created_at'] = now();
                $exam_data[] = $field;

            }

            Exam::insert($exam_data);
            $seminar = Seminar::with(["exams" => function($q){ 
                    $q->orderBy('question_no');
                }])->find($seminar_id);

        }

        return view('Exam.show',compact('seminar'));

    }

    public function store(Request $request){

        $user = Auth::user();

        if(!empty($request->seminar_use)){

            if(count($request->seminar_use) > 3 || count($request->seminar_use) < 3 ){
                return response()->json(['status' => false, 'message' => '講座で使用する問題は３つ選択してください']);
            }
        } 
        
        $exam_questions_count = 0;

        foreach($request->question_no as $key => $q){
            if(!empty($request->exam_question[$key]) && $request->exam_question[$key]!=''){
                $exam_questions_count +=1;
            }
        }

        if($exam_questions_count < 3){
            return response()->json(['status' => false, 'message' => '少なくとも 3 つの質問に入力して保存してください。']);
        }
        
        foreach($request->question_no as $key => $q){
            $seminar_use = 0;

            if(!empty($request->seminar_use) && !empty($request->seminar_use[$key])) $seminar_use = 1;

            Exam::where('id',$key)->update([
                'answer' => $request->answer[$key],
                'seminar_use' => $seminar_use,
                'exam_question' => $request->exam_question[$key],
                'updated_at' => now()
            ]);
        }

        return response()->json([
            'status' => true, 
            'message' => 'success', 
            'redirect' => route('seminar_exam.index')
        ]);


    }

    /**--- START Seminar Functions ---**/

    public function seminarDetail($seminar_id){
        $seminar = Seminar::with('seminarGroup')->where('id', $seminar_id)->firstorfail();

        return view('Exam.seminar_detail', compact('seminar'));
    }
    
    public function seminar_detail_edit($seminar_id){
        $seminar = Seminar::with('seminarGroup')->find($seminar_id);
        return view('Exam.seminar_detail_edit', compact('seminar'));
    }


    public function seminar_detail_edit_save(Request $request, $seminar_id){
        $validator = Validator::make($request->all(),[
            'category_no' => 'required',
            'category_name' => 'required',
            'seminar_title' => 'required',
            'teacher_name' => 'required',
            'teacher_affiliation1' => 'required',
            'place' => 'required',
            'capacity' => 'required',
            'registration_from' => 'required',
            'registration_to' => 'required',
            'seminar_date' => 'required',
            'start_at' => 'required',
            'end_at' => 'required',
            'reception_open_at' => 'required',
            'reception_close_at' => 'required',
        ]);

        if ($validator->fails()) {
            return  response()->json(['status' => false, 'error' => $validator->errors()]);
        }else{
            $seminar = Seminar::where('id', $seminar_id);

            $seminar->update(['category_no' => $request->category_no,
                     'category_name' => $request->category_name,
                     'seminar_title' => $request->seminar_title,
                     'teacher_name' => $request->teacher_name,
                     'teacher_affiliation1' => $request->teacher_affiliation1,
                     'place' => $request->place,
                     'capacity' => $request->capacity,
                     'seminar_date' => $request->seminar_date,
                     'start_at' => date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->start_at)),
                     'end_at' => date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->end_at)),
                     'reception_open_at' => date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->reception_open_at)),
                     'reception_close_at' => date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->reception_close_at)),]);

            $seminar->first()->seminarGroup()->update(['registration_from' =>$request->get('registration_from'), 'registration_to' => $request->get('registration_to')]);
            if ($seminar) {
                return response()->json(['status' => true, 'redirect' => route('seminar_exam.seminar_detail', $seminar_id) ]);
            }
        }

    }

    public function seminar_add(){
        return view('Exam.seminar_add');
    }

    public function seminarStore(Request $request){

        $user = Auth::user();

        $rules = [ 
           'category_no' => 'required',
            'category_name' => 'required',
            'seminar_title' => 'required',
            'teacher_name' => 'required',
            'teacher_affiliation1' => 'required',
            'place' => 'required',
            'capacity' => 'required',
            'registration_from' => 'required',
            'registration_to' => 'required',
            'seminar_date' => 'required',
            'start_at' => 'required',
            'end_at' => 'required',
            'reception_open_at' => 'required',
            'reception_close_at' => 'required',
        ];

        $message = [];

        $validator = \Validator::make($request->all(),$rules,$message);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'error' => $validator->errors()]);
        }

        $request->start_at = date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->start_at));
        $request->end_at = date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->end_at));
        $request->reception_open_at = date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->reception_open_at));
        $request->reception_close_at =  date('Y-m-d H:i:s', strtotime($request->seminar_date.' '.$request->reception_close_at));

        DB::beginTransaction();

        //create seminar group
        $seminar_group = SeminarGroup::create([
            'group_name' => $request->category_name,
            'registration_from' => $request->registration_from,
            'registration_to' => $request->registration_to,
        ]);

        //create seminars
        try {
           $seminar_group->seminars()->create($request->all());
        } catch (\Illuminate\Database\QueryException $exception) {
            $errorInfo = $exception->errorInfo;
            DB::rollBack();
            return response()->json(['status' => false, 'type' => 'dberror','error' => $errorInfo]);
        }

        //create seminar exams
        $exam_data = array();
        try {
           for($i = 1; $i <= 5; $i++){

                $field['m_seminar_id'] = $seminar_group->seminars[0]->id;
                $field['question_no'] = $i;
                $field['seminar_use'] = 0;
                $field['answer'] = 0;
                $field['created_at'] = now();
                $exam_data[] = $field;

            }
            Exam::insert($exam_data);
        } catch (\Illuminate\Database\QueryException $exception) {
            $errorInfo = $exception->errorInfo;
            DB::rollBack();
            return response()->json(['status' => false, 'type' => 'dberror','error' => $errorInfo]);
        }
        
        DB::commit();

        return response()->json(['status' => true, 'redirect' => route('seminar_exam.index')]);

    }

    /**--- END Seminar Functions ---**/

    /**--- Start Change Exam Answer---**/

    public function changeExam(){
        return view('Exam.change_exam');
    }

    public function changeExamList(Request $request){
        $seminar_data = array();

        $seminar_registrations = SeminarRegistration::whereHas('user', function($q) use($request) {
                    if($request->filled('fullname') && $request->fullname!=''){
                        $q->where(DB::raw("concat(l_name,'', f_name)"),'like','%'.str_replace(['　', ' '], '',$request->fullname).'%');
                    }})
                    ->whereHas('seminar', function($q) use($request) {
                        if($request->filled('date_from') && $request->filled('date_to')){
                            $q->whereBetween('seminar_date',[$request->date_from , $request->date_to]);
                        }})

resources/views/Exam/change_exam.blade.php
@extends('Layout.account.app')
@section('title', '回答内容変更')

@section('css')
<style type="text/css">

</style>
@endsection

@section('content')
	<div class="row justify-content-center mt-5">
		<div class="col-md-10 col-12">
        <div class="row">
				<!-- form label start -->
				<div class="col-md-12">
					<label class="page-title ">回答内容変更</label>
				</div>
        <div class="col-md-12 col-12">
           <div class="input-group mb-3 col-md-5 p-0 col-12">
            <div class="input-group-prepend bg-primary input-label">
              <span class="input-group-text bg-primary border-0" >氏名</span>
            </div>
            <input type="text"  class="form-control" name="fullname" id="fullname"  >
          </div>
				</div>
        <div class="col-md-4 col-7">
              <div class="input-group mb-3 p-0">
                <div class="input-group-prepend bg-primary input-label">
                  <span class="input-group-text bg-primary border-0" >開催日</span>
                </div>
                <input type="date"  class="form-control" name="date_from" id="date_from"  >
              </div>
        </div>
         <div class="col-md-6 col-3">
              <div class="input-group mb-3 p-0 col-5">
                <div class="input-group-prepend bg-white input-label">
                  <span class="input-group-text bg-white border-0 text-center px-2 mr-2" ><h3>~</h3></span>
                </div>
                <input type="date"  class="form-control" name="date_to" id="date_to"  >
              </div> 
        </div>
        <div class="col-md-12 text-right">
          <button type="button" class="btn btn-primary px-5" id="btn_search">検索</button>    
        </div>
        <div class="col-12 mt-3">
          <table class="table dt-responsive table-bordered" id="tbl_seminar" style="width: 100%;"></table>
        </div>
        <div class="col-sm-12 text-right mt-2">
          <a href="{{ route('account.index') }}" class="btn btn-warning ">戻る</a>
        </div>
			</div>
		</div>
	</div>
@endsection

@section('script')
<script type="text/javascript">

  $('#btn_search').on('click', function(){
     seminars();
  });

  var tbl_seminar;
  function seminars(){
    let fullname = $('#fullname').val();
    let date_from = $('#date_from').val();
    let date_to = $('#date_to').val();
    if (tbl_seminar) {
      tbl_seminar.clear();
      tbl_seminar.destroy()
    }

    tbl_seminar = $('#tbl_seminar').DataTable({
      serverSide: true,
      processing: true,
      pageLength: 10,
      ajax: {
          url : '{{ route("seminar_exam.exam_list") }}',
          data:{fullname: fullname, date_from: date_from, date_to: date_to},
          error: function (xhr, error, code) {
              //location.reload();
          }
       },
        searchable: false,
        "bLengthChange": false,
        "info": false,
        aaSorting: [],
        "bFilter": false,
        deferRender: false,
        language: {
        "emptyTable": "データなし",
        "paginate": {
          "previous": "前",
          "next": "次",
        }
      },
        columns: [{
        className: '',
        "orderable": false,
        "data": "user_name",
        "title": "氏名",
      },{
        className: '',
        "orderable": false,
        "data": "seminar_date",
        "title": "開催日",
      },{
        className: '',
        "orderable": false,
        "data": "category_no",
        "title": "領域",
      },{
        className: '',
        "orderable": false,
        "data": "category_name",
        "title": "セミナー項目",
      },{
        className: '',
        "orderable": false,
        "data": "answer_1",
        "title": "回答１",
      },{
        className: '',
        "orderable": false,
        "data": "answer_2",
        "title": "回答２",
      },{
         className: '',
        "orderable": false,
        "data": "answer_3",
        "title": "回答３",
      },{
        width: '',
        className: 'text-center',
        "data": "seminar_registration_id",
        "orderable": false,
        "title": "変更",
          "render": function(data, type, row, meta){
            newdata = '';
            newdata += '<a href="{{route('seminar_exam.exam_list_detail','')}}/'+row.seminar_registration_id+'" class="btn btn-primary btn-sm font-base mt-1 btn-block">変更</a> ';
            return newdata;
          }
        }
      ]
    });
  }
  seminars();

</script>
@endsection

resources/views/Exam/edit_exam.blade.php
@extends('Layout.account.app')
@section('title', '問題設定')

@section('css')
<style type="text/css">

</style>
@endsection

@section('content')
	<div class="row justify-content-center mt-5">
		<div class="col-md-6 col-12">
        <div class="row">
				<!-- form label start -->
				<div class="col-sm-12">
					<label class="page-title">{{ $seminar_registration->user->l_name."  ".$seminar_registration->user->f_name }}</label>
				</div>

				<div class="col-md-12 col-12">
                    <label>{{ $seminar_registration->seminar->seminar_date }} {{ $seminar_registration->seminar->category_no }} {{ $seminar_registration->seminar->category_name }}</label>
				</div>
                <form id="exam_form">
                    <div class="col-md-12 col-12 justify-content-center mt-4">
                        @csrf
                        <input type="hidden" name="seminar_registration_id" value="{{ $seminar_registration->id }}">
                        <div class="row">

                            @if(!$seminar_registration->userExams->isEmpty())  
                            @foreach($seminar_registration->userExams as $key => $eq)
                            <input type="hidden" name="user_exam_id[{{$eq->id}}]">
                                <input type="hidden" name="exam_id[{{$eq->id}}]" value="{{ $eq->exam_id }}">
                                
                                <div class="col-12 mb-2">
                                    <div class="row">

                                    <div class="col-3">問題{{ $key+=1 }}</div>

                                    <div class="col-3"> 
                                        <select class="form-control" name="answer[{{$eq->id}}]">
                                        <option value="0" {{ $eq->answer==0 ? 'selected' : '' }}>いいえ</option>
                                        <option value="1" {{ $eq->answer==1 ? 'selected' : '' }}>はい</option>
                                        </select>
                                    </div>
                                    </div>
                                </div>  

                            @endforeach
                            @else
                                
                            @endif


                            <div class="col-md-12 text-center mt-2 p-2">
                                <h5 class="error-div text-danger mb-5" style="display:none;"></h5>
                            </div>  
                                

                            <div class="col-md-12 text-right mt-2 p-2">
                            
                            <button type="submit" class="btn btn-primary">保存</button>
                            <a href="{{ route('seminar_exam.change_exam') }}" class="btn btn-warning">戻る</a>
                            </div>  
                            
                        </div>
                        
                    </div>
                </form>

      
			</div>
		</div>
	</div>
@endsection

@section('script')
<script type="text/javascript">


$("#exam_form").on('submit', function(e){
   e.preventDefault(e);

    const data = $('#exam_form').serialize();

    $('.error-div').hide();

    $.ajax({
        type:"POST",
        url: "{{ route('seminar_exam.exam_list_detail_store') }}",
        data:data,
        cache:false,
        beforeSend:function(){
            $(this).prop('disabled', true);
        },
        success:function(response){
          
          $(this).prop('disabled', false);
        
          if(response.status == true){
            window.location = response.redirect;
          }else{
            $('.error-div').text(response.message);
            $('.error-div').show();
          }           
      },
      error:function(error){
          console.log(error);
          $(this).prop('disabled', false);
      }
  });
});


</script>
@endsection

resources/views/Exam/index.blade.php
@extends('Layout.account.app')
@section('title', '講座情報')

@section('css')
<style type="text/css">

</style>
@endsection

@section('content')
	<div class="row justify-content-center mt-5">
		<div class="col-md-10 col-12">
        <div class="row justify-content-center">
				<!-- form label start -->
				<div class="col-sm-12">
					<label class="page-title">講座情報</label>
				</div>
				<div class="col-md-12 col-12">
		          <div class="form-inline">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="checkbox_con">
                        <label class="form-check-label" for="checkbox_con">
                            開催済みの講座も表示する
                        </label>
                    </div>
		          </div>
              <a href="{{ route('seminar_exam.seminar_add') }}" class="btn btn-primary btn-sm col-sm-3 col-5 mr-n2 float-right"> 新規講座登録</a>
				</div>
        <div class="col-12">
          <table class="table dt-responsive table-bordered" id="tbl_seminar" style="width: 100%;"></table>
        </div>
        <div class="col-sm-12 text-right mt-2">
          <a href="{{ route('account.index') }}" class="btn btn-warning">戻る</a>
        </div>
			</div>
		</div>
	</div>
@endsection

@section('script')
<script type="text/javascript">

  var tbl_seminar;
  function seminars(checkbox_con=false){

    if (tbl_seminar) {
      tbl_seminar.clear();
      tbl_seminar.destroy()
    }

    tbl_seminar = $('#tbl_seminar').DataTable({
      serverSide: true,
      processing: true,
      pageLength: 10,
      ajax: {
          url : '{{ route("seminar_exam.list") }}',
          data:{checkbox_con:checkbox_con},
          error: function (xhr, error, code) {
              //location.reload();
          }
       },
        searchable: false,
        "bLengthChange": false,
        "info": false,
        aaSorting: [],
        "bFilter": false,
        deferRender: false,
        language: {
        "emptyTable": "データなし",
        "paginate": {
          "previous": "前",
          "next": "次",
        }
      },
        columns: [{
        className: '',
        "orderable": false,
        "data": "seminar_date",
        "title": "開催日",
      },{
        className: '',
        "orderable": false,
        "data": "category_no",
        "title": "領域",
      },{
        className: '',
        "orderable": false,
        "data": "category_name",
        "title": "セミナー項目",
      },{
        className: '',
        "orderable": false,
        "data": "teacher_name",
        "title": "講師名",
      },{
        className: '',
        "orderable": false,
        "data": "teacher_affiliation1",
        "title": "講師肩書",
      },{
        width: '',
        className: 'text-center',
        "data": "id",
        "orderable": false,
        "title": "編集",
          "render": function(data, type, row, meta){
            newdata = '';
            newdata += '<a href="{{route('seminar_exam.seminar_detail','')}}/'+row.id+'" class="btn btn-primary btn-sm font-base mt-1 btn-block">詳細</a> ';
            return newdata;
          }
        },{
        width: '',
        className: 'text-center',
        "data": "id",
        "orderable": false,
        "title": "問題",
          "render": function(data, type, row, meta){
            newdata = '';
            newdata += '<a href="{{route('seminar_exam.show','')}}/'+row.id+'" class="btn btn-primary btn-sm font-base mt-1 btn-block">問題</a> ';
            return newdata;
          }
        }
      ]
    });
  }
  seminars();

  $("#checkbox_con").change(function(){
     seminars(this.checked);
  });

</script>
@endsection